# Generated by Django 5.2.5 on 2025-08-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='производитель', max_length=40, verbose_name='Производитель')),
                ('number', models.CharField(help_text='номер подшипника', max_length=40, verbose_name='Номер подшипника')),
                ('slug', models.SlugField(help_text='URL', unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, help_text='изображение', null=True, upload_to='source/bearings/', verbose_name='Изображение')),
                ('element_type', models.CharField(choices=[('B', 'Шариковый'), ('R', 'Роликовый'), ('S', 'Скольжения')], help_text='тип подшипника', max_length=1, verbose_name='Тип подшипника')),
                ('outer_diameter', models.PositiveIntegerField(blank=True, help_text='наружный диаметр', null=True, verbose_name='Наружный диаметр')),
                ('inner_diameter', models.PositiveIntegerField(blank=True, help_text='внутренный диаметр', null=True, verbose_name='Внутренный диаметр')),
            ],
            options={
                'verbose_name': 'Подшипник',
                'verbose_name_plural': 'Подшипники',
                'ordering': ['manufacturer', 'number'],
                'indexes': [models.Index(fields=['manufacturer', 'number'], name='storage_bea_manufac_2aa089_idx')],
            },
        ),
    ]
