# Generated by Django 5.2.5 on 2025-08-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='производитель', max_length=40, verbose_name='Производитель')),
                ('assembly_code', models.CharField(help_text='код сборки', max_length=40, verbose_name='Код сборки')),
                ('slug', models.SlugField(help_text='URL', unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, help_text='изображение', null=True, upload_to='source/mech_seals/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Торцевое уплотнение',
                'verbose_name_plural': 'Торцевые уплотнения',
                'ordering': ['manufacturer', 'assembly_code'],
                'indexes': [models.Index(fields=['manufacturer', 'assembly_code'], name='storage_mec_manufac_45ad5a_idx')],
            },
        ),
    ]
