# Generated by Django 5.2.5 on 2025-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_mechseal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearing',
            name='image',
            field=models.ImageField(blank=True, help_text='изображение', null=True, upload_to='storage/bearings/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mechseal',
            name='image',
            field=models.ImageField(blank=True, help_text='изображение', null=True, upload_to='storage/mech_seals/', verbose_name='Изображение'),
        ),
    ]
