# Generated by Django 5.2.5 on 2025-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_bearing_image_alter_mechseal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechseal',
            options={'ordering': ['manufacturer', 'label', 'assembly_code'], 'verbose_name': 'Торцевое уплотнение', 'verbose_name_plural': 'Торцевые уплотнения'},
        ),
        migrations.RemoveIndex(
            model_name='mechseal',
            name='storage_mec_manufac_45ad5a_idx',
        ),
        migrations.AddField(
            model_name='mechseal',
            name='label',
            field=models.CharField(blank=True, help_text='марка ТУ', max_length=40, null=True, verbose_name='Марка ТУ'),
        ),
        migrations.AddField(
            model_name='mechseal',
            name='material_id',
            field=models.CharField(blank=True, help_text='id материала', max_length=40, null=True, verbose_name='ID материала'),
        ),
        migrations.AddField(
            model_name='mechseal',
            name='repair_kit_id',
            field=models.CharField(blank=True, help_text='id ремонтного комплекта', max_length=40, null=True, verbose_name='ID ремонтного комплекта'),
        ),
        migrations.AddIndex(
            model_name='mechseal',
            index=models.Index(fields=['manufacturer', 'label', 'assembly_code'], name='storage_mec_manufac_3c30a1_idx'),
        ),
    ]
