# Generated by Django 5.2.5 on 2025-08-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='категория оборудования', max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='описание', null=True, verbose_name='Описание')),
                ('slug', models.CharField(help_text='URL', max_length=50, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, help_text='изображение категории', null=True, upload_to='equipment_categories/', verbose_name='Изображение')),
                ('parent', models.ForeignKey(blank=True, help_text='родительская категория', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='позиция оборудования', max_length=25, unique=True, verbose_name='Позиция')),
                ('label', models.CharField(db_index=True, help_text='название оборудования', max_length=50, verbose_name='Название')),
                ('inventory_number', models.CharField(blank=True, help_text='инвентарный номер', max_length=20, null=True, unique=True, verbose_name='Инвентарный номер')),
                ('slug', models.SlugField(help_text='URL', unique=True, verbose_name='Адресная строка')),
                ('description', models.TextField(blank=True, help_text='описание', null=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='изображение', upload_to='source/equipment/pics/%Y/%m/%d', verbose_name='Изображение')),
                ('category', models.ForeignKey(help_text='категория оборудования', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.category')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['position', 'label'],
                'indexes': [models.Index(fields=['inventory_number'], name='equipment_e_invento_3592e9_idx'), models.Index(fields=['position'], name='equipment_e_positio_c46fc7_idx')],
            },
        ),
    ]
