# Generated by Django 5.2.5 on 2025-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_category_options'),
        ('storage', '0002_mechseal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bearings',
            field=models.ManyToManyField(blank=True, help_text='подшипники', to='storage.bearing'),
        ),
    ]
