# Generated by Django 5.2.5 on 2025-08-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_category_bearings'),
        ('storage', '0002_mechseal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bearings',
        ),
        migrations.AddField(
            model_name='equipment',
            name='bearings',
            field=models.ManyToManyField(blank=True, help_text='подшипники', null=True, to='storage.bearing'),
        ),
    ]
