# Generated by Django 5.2.5 on 2025-08-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_category_bearings_equipment_bearings'),
        ('storage', '0003_alter_bearing_image_alter_mechseal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='производитель оборудования', max_length=50, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mech_seal',
            field=models.ForeignKey(blank=True, help_text='торцевое уплотнение', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mech_seal', to='storage.mechseal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='изображение категории', null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(help_text='изображение', upload_to='equipment/', verbose_name='Изображение'),
        ),
    ]
